// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB72G3s9ymyCEn1iOR7_WjIiNSMLeW2b8k',
    appId: '1:338927356213:android:3492063ee953545098e47c',
    messagingSenderId: '338927356213',
    projectId: 'gwcorp-ihs',
    storageBucket: 'gwcorp-ihs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy11cOc0VWduOYkfAmKtv0xkzTKe8sY3o',
    appId: '1:338927356213:ios:3096a3e02dcee16398e47c',
    messagingSenderId: '338927356213',
    projectId: 'gwcorp-ihs',
    storageBucket: 'gwcorp-ihs.firebasestorage.app',
    androidClientId: '338927356213-6tlrpgfmpbg9u29v812gs8rbr98m2es8.apps.googleusercontent.com',
    iosClientId: '338927356213-rftgd9lb7nnlc6fed9rtr56hpm2grl74.apps.googleusercontent.com',
    iosBundleId: 'GWCORP.GWCORP',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFGOHZnmt8QbaJJN-FEt7pGTR8yPrYaPI',
    appId: '1:338927356213:web:c86211f5406d001198e47c',
    messagingSenderId: '338927356213',
    projectId: 'gwcorp-ihs',
    authDomain: 'gwcorp-ihs.firebaseapp.com',
    storageBucket: 'gwcorp-ihs.firebasestorage.app',
    measurementId: 'G-MQB26QCDQP',
  );
}
